### ISSUE TITLE
Multiplayer Crash

### ISSUE THREAD

**Issue by LuziferSenpai** [raiguard/Factorio-RecipeBook#10]
The mod Recipe Book (1.3.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_tick (ID 0)
RecipeBook/scripts/search.lua:18: bad argument #2 of 2 to 'get_player' (string expected, got nil)
stack traceback:
    [C]: in function 'get_player'
    RecipeBook/scripts/search.lua:18: in function 'iterate'
    RecipeBook/scripts/on-tick.lua:16: in function <RecipeBook/scripts/on-tick.lua:8>

how to reproduce the error:
- be on a server with a friend (or someone)
- control+b both of them
- enjoy the crash

**Comment by raiguard** [comment]
I'm unable to reproduce this error. Could you please send me a save file?

**Comment by LuziferSenpai** [comment]
https://we.tl/t-Lhf4Vj9k0B

**Comment by Firerazer** [comment]
Hello,
Didn't saw it was a github report, I would have done it myself instead of asking luzifer ;)
We have reproduced this crash twice with this save game at different places and moments during the save.
Was Factorio 0.18.28, all mods updated to last version, auto-hosted game.
We switched from FNEI that was causing desyncs also since a long time, hope this one will allow a safe MP experience :)

**Comment by raiguard** [comment]
I _STILL_ can't reproduce it on a multiplayer session with that save file... I'll see what I can do.
