### ISSUE TITLE
3.4.0 incompatible with flib >= 0.11.0

### ISSUE THREAD

**Issue by SegFaulty** [raiguard/Factorio-RecipeBook#114]
mod was deactived after todays update

with Message _"These mod is incompatible with flib >= 0.11.0"_

seems not by intend, because flib is widely used

---------------------------
i do not understand the problem, because info.json currently says:  `"dependencies": ["? base >= 1.1.41", "flib >= 0.11.0"],`
may be there is already a fixed version 3.4.1 on the way ... idn

**Comment by SegFaulty** [comment]
okay.. now i understand
mod requires flib 0.11.0 but the current released flib version is 0.10.1

**Comment by SegFaulty** [comment]
temporary fix:
 info.json
` "dependencies": ["? base >= 1.1.41", "flib >= 0.10.0"],`

**Comment by Zeroji** [comment]
I have the same issue, I can also confirm that changing `info.json` fixes it.

Here's the commit that introduced the bug: 9ed296cf57726c3bff59fd954ef164d7d198db42
The problem is that flib 0.11.0 exists but is not released yet, see https://github.com/factoriolib/flib/commit/925b66b3123af281a71752027fcad2c4d7ffa061

**Comment by msamsel** [comment]
I get the same issue 😭
Thx for the tips

**Comment by raiguard** [comment]
Sorry for the mixup everyone.

**Comment by msamsel** [comment]
That was fast reaction time ❤️
