### ISSUE TITLE
List what recipes a building can craft

### ISSUE THREAD

**Issue by dbeckwith** [raiguard/Factorio-RecipeBook#28]
Seeing what buildings a recipe is made in is helpful, but often I want to see the reverse as well. I might have just unlocked a new building and am wondering, "What do I use this for? What can I make in it?" It would be great if the material page for a building showed what recipes it can craft. This is especially useful for things like pumps or furnaces or Krastorio's crusher where you don't select a recipe so you can't easily see a list of all the recipes it makes.

Love the mod by the way!

**Comment by raiguard** [comment]
The original version of this mod had this capability, but unfortunately it has problems. With large modpacks (or even in the vanilla game), a crafter can potentially support hundreds, if not thousands, of recipes. This would lag out the game whenever someone would open the screen, and was pretty useless because there was no good way to navigate the list.

What I _can_ do is list all of the categories that a crafter supports, then you can use the settings panel to show only those categories. That will limit search and information to things of that category, which may help with this.

Thanks for using the mod!

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/91689318-14955300-eb21-11ea-9515-49e5a4886da2.png)

**Comment by dbeckwith** [comment]
Okay that sounds like a good solution, thanks!
