### ISSUE TITLE
Script.dat bloat/High memory usage

### ISSUE THREAD

**Issue by oorzkws** [raiguard/Factorio-RecipeBook#56]
#### Describe the Bug

When using mods that result in a significant amount of recipes, Recipe Book will use a large amount of memory and increase the save time to a bothersome amount. To illustrate, script.dat from my personal save is 60mb without RB but 230 with.

#### To Reproduce

1. Install mods with a high amount of recipes, such as full pysuite plus omnicompression
2. Install recipebook
3. Enter game and observe save times
4. Remove recipebook
5. Enter game and observe save times

#### Save file & Username

[RecipeBookBugReport.zip](https://github.com/raiguard/Factorio-RecipeBook/files/6892471/RecipeBookBugReport.zip) Username is `_-_-_`

#### Log file
[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/6892472/factorio-current.log)

**Comment by raiguard** [comment]
170mb seems like more than it should be, I'll take a look. However, Recipe Book simply keeps a _lot_ of data, and the amount of data stored will only ever increase, not decrease. For example, v3.0.0 that I'm currently writing will probably double the amount of data Recipe Book keeps in global. There's no way around it - there's simply that much data that it takes care of.

The biggest culprit here is translations. Unfortunately, Factorio doesn't allow mods to read translations directly from the game, because it's not deterministic. So we have to use a convoluted method of requesting a translation and getting it back in an event some time later, then we have to store it. Thus, Recipe Book stores the names and descriptions of every crafter, fluid, item, recipe, and technology in the game in the script data. There's literally no way around it without some major changes by the Factorio devs.

In all, I think there's not gonna be anything I can do about this, but I'll take a look to see if something is amiss.

**Comment by raiguard** [comment]
I loaded up Py and Omni, and did some checks. That modset has 29 THOUSAND RECIPES. That's why there is so much global data. Recipe Book keeps data on every recipe, and if you have a lot of recipes, there's going to be lots of data.

There's nothing I can do about this. Sorry.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/127387657-6b091fab-7920-494b-894c-4b05ebaac48b.png)

This is just a lot of data for RB to handle. It's just going to take a while to save and load it all.

**Comment by raiguard** [comment]
Well actually, I might be able to do something about this after all. I'm experimenting with only keeping the bare minimum amount of data in `global`, and generating the RB data for each client individually when they load the save. It's looking promising.

**Comment by raiguard** [comment]
Alright, drumroll please...
I made the changes and they worked flawlessly! After solving some dependency loops, everything just worked like a charm.

Before: 102 MB
After: 9.3 MB

There's still going to be a non-trivial amount of data, especially with a modset this large. RB still has to store translations for every single thing it has data for in the script data. But the translations take up a small portion of the overall space, so it's still a >10x improvement.

Thanks for bringing this to my attention!

**Comment by raiguard** [comment]
v3.0 includes massive data storage optimizations, so this issue can now be closed.

**Comment by oorzkws** [comment]
Wow, thank you giving it a try. That's made a very large difference in my save times! ❤️
