### ISSUE TITLE
Hide Transport Drone Recipes

### ISSUE THREAD

**Issue by millerlarson** [raiguard/Factorio-RecipeBook#8]
Is there a way to hide the recipes included with Transport Drones mod? 
Or perhaps a mod setting that I'm overlooking that could hide these?

Wasting a lot of time/clicks by guessing which search result is the "real" recipe and which is from Transport Drones.

**Comment by raiguard** [comment]
Yeah, this is a known problem. Unfortunately Transport Drones (and Mining Drones) don't "hide" these recipes, so there's no easy way to tell which ones should be hidden. It'll require manually adding support for those mods.

I'll get it done for the next version.

**Comment by millerlarson** [comment]
Yikes, that is unfortunate.  Any efforts along these lines would be greatly appreciated.

**Comment by raiguard** [comment]
So, turns out that it was fairly trivial to do this, because transport drones assigned each recipe to a custom category. I now have a small list of excluded categories, and the transport drones recipes no longer show up.

In the future I will add a remote interface for telling Recipe Book to exclude a category or object, so mod authors can customize which of their mod's stuff will show up.

**Comment by millerlarson** [comment]
This is great, thank you!

**Comment by raiguard** [comment]
This is out in the most recent version!
